site_name: Builelib Manual
site_description: Builelib Manual
site_url: https://masatomiyata.github.io/builelib/
site_dir: docs
docs_dir: docs-md

nav:
  - Builelib:
      - Overview: index.md
  - How to use:
      - How to run: installation.md
      - InputSheet: InputSheet.md
  - Reference:
      - Calculation Logic: logic.md
  - License: license.md

theme:
  name: material
  language: ja
  icon:
    logo: material/library 
    repo: fontawesome/brands/git-alt
  palette:
    - schema: default
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - toc.integrate     # 目次を右側ではなく、ページ内に表示
    - navigation.expand   # サイドバーのナビゲーションを展開
    - navigation.instant  # ページ遷移を高速化
    - navigation.top
  font:
    text: Roboto       # 本文用フォント
    code: Roboto Mono  # コードブロック用フォント

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MasatoMiyata/builelib
  generator: false
  alternate:
    - name: English
      link: ./en/index.html
      lang: en
    - name: 日本語
      link: ./index.html
      lang: jp

extra_css:
  - assets/custom.css
  - https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap
  - https://fonts.googleapis.com/css?family=Roboto+Mono:400,700&display=swap

extra_javascript:
  - js/mathjax.js
  - js/mathjax-reload.js
  - js/lang-switch.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# マークダウンの拡張機能
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition:
  - codehilite:
      linenums: true
      guess_lang: false
      use_pygments: false
      noclasses: true
  - tables:
  - attr_list:
  - md_in_html:
      
# Copyright
copyright: 'Copyright© 2019-2025 : Masato Miyata'